export const OCEAN_EVIDENCE = Object.freeze([
    Object.freeze({ id: 'moon-seismic-evidence', icon: '〰', copy: Object.freeze({ pt: { title: 'Lua · vibrações', known: 'Sensores afastados localizam impactos ao comparar o tempo das ondas.', search: 'Isto ensina-nos a ouvir um mundo, mas não prova que exista um oceano.' }, en: { title: 'Moon · vibrations', known: 'Separated sensors locate impacts by comparing wave timing.', search: 'This teaches us to listen to a world, but does not prove an ocean exists.' } }) }),
    Object.freeze({ id: 'europa-ocean-evidence', icon: '≋', copy: Object.freeze({ pt: { title: 'Europa · eco profundo', known: 'O radar encontra uma fronteira compatível com líquido debaixo do gelo.', search: 'Ainda precisamos de medir diretamente esse material.' }, en: { title: 'Europa · deep echo', known: 'Radar finds a boundary compatible with liquid beneath the ice.', search: 'We still need to measure that material directly.' } }) }),
    Object.freeze({ id: 'enceladus-plume-evidence', icon: '✣', copy: Object.freeze({ pt: { title: 'Encélado · cristais', known: 'As plumas trazem gelo e sais de um oceano subterrâneo até ao espaço.', search: 'Uma amostra interessante não é uma descoberta de vida.' }, en: { title: 'Enceladus · crystals', known: 'Plumes carry ice and salts from an underground ocean into space.', search: 'An interesting sample is not a discovery of life.' } }) }),
    Object.freeze({ id: 'titan-chemistry-evidence', icon: '◇', copy: Object.freeze({ pt: { title: 'Titã · química', known: 'Titã tem química orgânica, nuvens, chuva, rios e lagos de metano.', search: 'Ter ingredientes e líquidos não significa ter seres vivos.' }, en: { title: 'Titan · chemistry', known: 'Titan has organic chemistry, clouds, rain, rivers and methane lakes.', search: 'Having ingredients and liquids does not mean having living things.' } }) })
]);

export const OCEAN_CONCLUSIONS = Object.freeze([
    Object.freeze({ id: 'aliens-everywhere', correct: false, copy: Object.freeze({ pt: 'Encontrámos seres vivos em todas as luas.', en: 'We found living things on every moon.' }) }),
    Object.freeze({ id: 'potential-not-proof', correct: true, copy: Object.freeze({ pt: 'Alguns mundos têm condições interessantes para a vida, mas habitável não significa habitado.', en: 'Some worlds have interesting conditions for life, but habitable does not mean inhabited.' }) }),
    Object.freeze({ id: 'all-liquids-water', correct: false, copy: Object.freeze({ pt: 'Todos os líquidos encontrados são oceanos de água.', en: 'Every liquid we found is a water ocean.' }) })
]);
